function speedOptimize(text) {
  document.getElementById("rocket-conatainer").style.display = "flex";
  document.getElementById("rocket-conatainer").style.opacity = 1;
  const rocketText = document.querySelector("#opration");
  if (rocketText) {
    rocketText.textContent = text;
  }

  const commands = [
    'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Scheduler" /v "VsyncIdleTimeout" /t REG_DWORD /d "0" /f',
    'Reg.exe add "HKCU\\System\\GameConfigStore" /v "GameDVR_Enabled" /t REG_DWORD /d "0" /f',
    'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR" /v "AppCaptureEnabled" /t REG_DWORD /d "0" /f',
    'Reg.exe add "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR" /v "AllowgameDVR" /t REG_DWORD /d "0" /f',
    'Reg.exe add "HKLM\\SOFTWARE\\Intel\\GMM" /v "DedicatedSegmentSize" /t REG_DWORD /d "1298" /f',
    'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "Win32PrioritySeparation" /t REG_DWORD /d "38" /f',
    'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "IRQ8Priority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "IRQ16Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "Win32PrioritySeparation" /t REG_DWORD /d "38" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "IRQ8Priority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "IRQ16Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnablePrefetcher" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableSuperfetch" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableBoottrace" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoLowDiskSpaceChecks" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "LinkResolveIgnoreLinkInfo" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoResolveSearch" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoResolveTrack" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoInternetOpenWith" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NtfsMftZoneReservation" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NTFSDisable8dot3NameCreation" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "DontVerifyRandomDrivers" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NTFSDisableLastAccessUpdate" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "ContigFileAllocSize" /t REG_DWORD /d "64" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "AutoEndTasks" /t REG_SZ /d "1" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "MenuShowDelay" /t REG_SZ /d "0" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "WaitToKillAppTimeout" /t REG_SZ /d "5000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "WaitToKillServiceTimeout" /t REG_SZ /d "1000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "HungAppTimeout" /t REG_SZ /d "4000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "LowLevelHooksTimeout" /t REG_SZ /d "1000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "ForegroundLockTimeout" /t REG_SZ /d "150000" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsAll" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "GameFluidity" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsStatusGames" /t REG_DWORD /d "16" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsStatusGamesAll" /t REG_DWORD /d "4" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Affinity" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Background Only" /t REG_SZ /d "False" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Clock Rate" /t REG_DWORD /d "10000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "GPU Priority" /t REG_DWORD /d "8" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Scheduling Category" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "SFIO Priority" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Latency Sensitive" /t REG_SZ /d "True" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Affinity" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Background Only" /t REG_SZ /d "False" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Clock Rate" /t REG_DWORD /d "10000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "GPU Priority" /t REG_DWORD /d "8" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Scheduling Category" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "SFIO Priority" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Latency Sensitive" /t REG_SZ /d "True" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "CPUPriority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "FastDRAM" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "PCIConcur" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "AGPConcur" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "Max Cached Icons" /t REG_SZ /d "2000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "AlwaysUnloadDLL" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\AlwaysUnloadDLL" /v "Default" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "EnableBalloonTips" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\MSMQ\\Parameters" /v "TCPNoDelay" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMin" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMax" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMax" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMin" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet002\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMax" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet002\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\0cc5b647-c1df-4637-891a-dec35c318583" /v "ValueMin" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power" /v "HibernateEnabled" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power" /v "HiberbootEnabled" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\893dee8e-2bef-41e0-89c6-b55d0929964c" /v "ValueMax" /t REG_DWORD /d "100" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerSettings\\54533251-82be-4824-96c1-47b60b740d00\\893dee8e-2bef-41e0-89c6-b55d0929964c\\DefaultPowerSchemeValues\\8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c" /v "ValueMax" /t REG_DWORD /d "100" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Scheduler" /v "VsyncIdleTimeout" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKCU\\System\\GameConfigStore" /v "GameDVR_Enabled" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR" /v "AppCaptureEnabled" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR" /v "AllowgameDVR" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Intel\\GMM" /v "DedicatedSegmentSize" /t REG_DWORD /d "1298" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "Win32PrioritySeparation" /t REG_DWORD /d "38" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "IRQ8Priority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl" /v "IRQ16Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "Win32PrioritySeparation" /t REG_DWORD /d "38" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "IRQ8Priority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl" /v "IRQ16Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnablePrefetcher" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableSuperfetch" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableBoottrace" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoLowDiskSpaceChecks" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "LinkResolveIgnoreLinkInfo" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoResolveSearch" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoResolveTrack" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "NoInternetOpenWith" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NtfsMftZoneReservation" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NTFSDisable8dot3NameCreation" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "DontVerifyRandomDrivers" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "NTFSDisableLastAccessUpdate" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" /v "ContigFileAllocSize" /t REG_DWORD /d "64" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "AutoEndTasks" /t REG_SZ /d "1" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "MenuShowDelay" /t REG_SZ /d "0" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "WaitToKillAppTimeout" /t REG_SZ /d "5000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "WaitToKillServiceTimeout" /t REG_SZ /d "1000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "HungAppTimeout" /t REG_SZ /d "4000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "LowLevelHooksTimeout" /t REG_SZ /d "1000" /f',
  'Reg.exe add "HKCU\\Control Panel\\Desktop" /v "ForegroundLockTimeout" /t REG_SZ /d "150000" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsAll" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "GameFluidity" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsStatusGames" /t REG_DWORD /d "16" /f',
  'Reg.exe add "HKCU\\SOFTWARE\\Microsoft\\Games" /v "FpsStatusGamesAll" /t REG_DWORD /d "4" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Affinity" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Background Only" /t REG_SZ /d "False" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Clock Rate" /t REG_DWORD /d "10000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "GPU Priority" /t REG_DWORD /d "8" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Scheduling Category" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "SFIO Priority" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games" /v "Latency Sensitive" /t REG_SZ /d "True" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Affinity" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Background Only" /t REG_SZ /d "False" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Clock Rate" /t REG_DWORD /d "10000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "GPU Priority" /t REG_DWORD /d "8" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Priority" /t REG_DWORD /d "2" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Scheduling Category" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "SFIO Priority" /t REG_SZ /d "High" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency" /v "Latency Sensitive" /t REG_SZ /d "True" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "CPUPriority" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "FastDRAM" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "PCIConcur" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\System\\CurrentControlSet\\Services\\VxD\\BIOS" /v "AGPConcur" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "Max Cached Icons" /t REG_SZ /d "2000" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "AlwaysUnloadDLL" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\AlwaysUnloadDLL" /v "Default" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "EnableBalloonTips" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SOFTWARE\\Microsoft\\MSMQ\\Parameters" /v "TCPNoDelay" /t REG_DWORD /d "1" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnablePrefetcher" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableSuperfetch" /t REG_DWORD /d "0" /f',
  'Reg.exe add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableBoottrace" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v SmartScreenEnabled /t REG_SZ /d "Off" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\AppHost" /v ContentEvaluation /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\System" /v "EnableActivityFeed" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\Power\\PowerThrottling" /v "PowerThrottlingOff" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\CTF\\LangBar" /v "ShowStatus" /t REG_DWORD /d "3" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\CTF\\LangBar" /v "ExtraIconsOnMinimized" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\CTF\\LangBar" /v "Transparency" /t REG_DWORD /d "255" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\CTF\\LangBar" /v "Label" /t REG_DWORD /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "MouseHoverTime" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "MouseSpeed" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "MouseThreshold1" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "MouseThreshold2" /t REG_SZ /d "0" /f',
  'REG ADD "HKCU\\Control Panel\\Mouse" /v "MouseSpeed" /t REG_SZ /d "0" /f',
  'REG ADD "HKCU\\Control Panel\\Mouse" /v "MouseThreshold1" /t REG_SZ /d "0" /f',
  'REG ADD "HKCU\\Control Panel\\Mouse" /v "MouseThreshold2" /t REG_SZ /d "0" /f',
  'REG ADD "HKCU\\Control Panel\\Mouse" /v "MouseSensitivity" /t REG_SZ /d "10" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Desktop" /v "ForegroundLockTimeout" /t REG_DWORD /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Desktop" /v "MenuShowDelay" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Desktop" /v "MouseWheelRouting" /t REG_DWORD /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "Beep" /t REG_SZ /d "No" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Mouse" /v "ExtendedSounds" /t REG_SZ /d "No" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Sound" /v "Beep" /t REG_SZ /d "no" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Sound" /v "ExtendedSounds" /t REG_SZ /d "no" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\HighContrast" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\Keyboard Response" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\MouseKeys" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\SoundSentry" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\StickyKeys" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\TimeOut" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Accessibility\\ToggleKeys" /v "Flags" /t REG_SZ /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "NavPaneShowAllFolders" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\Bags\\AllFolders\\Shell" /v "FolderType" /t REG_SZ /d "NotSpecified" /f',
  'REG DELETE "HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\Bags" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "link" /t REG_BINARY /d "00000000" /f',
  'REG ADD "HKCU\\Control Panel\\Accessibility\\MouseKeys" /v "Flags" /t REG_SZ /d "186" /f',
  'REG ADD "HKCU\\Control Panel\\Accessibility\\MouseKeys" /v "MaximumSpeed" /t REG_SZ /d "40" /f',
  'REG ADD "HKCU\\Control Panel\\Accessibility\\MouseKeys" /v "TimeToMaximumSpeed" /t REG_SZ /d "3000" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Explorer" /v "NoDataExecutionPrevention" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\System" /v "DisableHHDEP" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\System" /v "EnableSmartScreen" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance" /v "MaintenanceDisabled" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Power" /v "HiberbootEnabled" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power" /v "SleepStudyDisabled" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "DisallowShaking" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Attachments" /v "SaveZoneInformation" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\MRT" /v "DontOfferThroughWUAU" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU" /v "AUOptions" /t REG_DWORD /d "2" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\Windows Error Reporting" /v "Disabled" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Control Panel\\Desktop" /v "MenuShowDelay" /t REG_SZ /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\CrashControl" /v "DisplayParameters" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer" /v "DisableNotificationCenter" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "Start_TrackDocs" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer" /v "DisableSearchBoxSuggestions" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Services\\LanmanServer\\Parameters" /v "AutoShareWks" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Keyboard Layout\\Toggle" /v "Language Hotkey" /t REG_SZ /d "3" /f',
  'REG ADD "HKCU\\Keyboard Layout\\Toggle" /v "Hotkey" /t REG_SZ /d "3" /f',
  'REG ADD "HKCU\\Keyboard Layout\\Toggle" /v "Layout Hotkey" /t REG_SZ /d "3" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FlyoutMenuSettings" /v "ShowSleepOption" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FlyoutMenuSettings" /v "ShowLockOption" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Multimedia\\Audio" /v "UserDuckingPreference" /t REG_DWORD /d "3" /f',
  'REG ADD "HKCU\\AppEvents\\Schemes" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System" /v "DelayedDesktopSwitchTimeout" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI\\BootAnimation" /v "DisableStartupSound" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "Start_LargeMFUIcons" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects" /v "VisualFXSetting" /t REG_DWORD /d "2" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Gwx" /v "DisableGwx" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate" /v "DisableOSUpgrade" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance" /v "MaintenanceDisabled" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnablePrefetcher" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters" /v "EnableSuperfetch" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer" /v "EnableAutoTray" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\CloudContent" /v "DisableWindowsConsumerFeatures" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\WUDF" /v "LogEnable" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\WUDF" /v "LogLevel" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Peernet" /v "Disabled" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Internet Explorer\\Main" /v "DEPOff" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System" /v "VerboseStatus" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize" /v "StartupDelayInMSec" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\TabletPC" /v "TurnOffPenFeedback" /t REG_DWORD /d "1" /f',
  'REG ADD "HKU\\.DEFAULT\\Control Panel\\Desktop" /v "MenuShowDelay" /t REG_SZ /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\Remote Assistance" /v "fAllowToGetHelp" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Control Panel\\International\\User Profile" /v "HttpAcceptLanguageOptOut" /t REG_DWORD /d "1" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo" /v "Enabled" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\AppHost" /v "EnableWebContentEvaluation" /t REG_DWORD /d "0" /f',
  'REG ADD "HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer" /v "DisableNotificationCenter" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowAutoConnectToWiFiSenseHotspots" /v "value" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowWiFiHotSpotReporting" /v "value" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\DeliveryOptimization\\Config" /v "DownloadMode" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\ImmersiveShell" /v "UseActionCenterExperience" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection" /v "AllowTelemetry" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer" /v "HideSCAHealth" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\AdvertisingInfo" /v "DisabledByGroupPolicy" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\DataCollection" /v "AllowTelemetry" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\EnhancedStorageDevices" /v "TCGSecurityActivationDisabled" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\OneDrive" /v "DisableFileSyncNGSC" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\safer\\codeidentifiers" /v "authenticodeenabled" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\SettingSync" /v "DisableSettingSync" /t REG_DWORD /d "2" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\SettingSync" /v "DisableSettingSyncUserOverride" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Error Reporting" /v "DontSendAdditionalData" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "AllowCortana" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "AllowIndexingEncryptedStoresOrItems" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "AllowSearchToUseLocation" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "AlwaysUseAutoLangDetection" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "ConnectedSearchUseWeb" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\Software\\Policies\\Microsoft\\Windows\\Windows Search" /v "DisableWebSearch" /t REG_DWORD /d "1" /f',
  'REG ADD "HKLM\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection" /v "AllowTelemetry" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\WMI\\AutoLogger\\AutoLogger-Diagtrack-Listener" /v "Start" /t REG_DWORD /d "0" /f',
  'REG ADD "HKLM\\System\\CurrentControlSet\\Control\\WMI\\AutoLogger\\SQMLogger" /v "Start" /t REG_DWORD /d "0" /f',    
  'sc config ALG start=disabled',
  'sc config AJRouter start=disabled',
  'sc config XblAuthManager start=disabled',
  'sc config XblGameSave start=disabled',
  'sc config XboxNetApiSvc start=disabled',
  'sc config WSearch start=disabled',
  'sc config lfsvc start=disabled',
  'sc config RemoteRegistry start=disabled',
  'sc config WpcMonSvc start=disabled',
  'sc config SEMgrSvc start=disabled',
  'sc config SCardSvr start=disabled',
  'sc config Netlogon start=disabled',
  'sc config icssvc start=disabled',
  'sc config wisvc start=disabled',
  'sc config RetailDemo start=disabled',
  'sc config WalletService start=disabled',
  'sc config Fax start=disabled',
  'sc config WbioSrvc start=disabled',
  'sc config iphlpsvc start=disabled',
  'sc config wcncsvc start=disabled',
  'sc config fhsvc start=disabled',
  'sc config PhoneSvc start=disabled',
  'sc config seclogon start=disabled',
  'sc config FrameServer start=disabled',
  'sc config WbioSrvc start=disabled',
  'sc config StiSvc start=disabled',
  'sc config PcaSvc start=disabled',
  'sc config DPS start=disabled',
  'sc config MapsBroker start=disabled',
  'sc config bthserv start=disabled',
  'sc config BDESVC start=disabled',
  'sc config BthAvctpSvc start=disabled',
  'sc config WpcMonSvc start=disabled',
  'sc config DiagTrack start=disabled',
  'sc config CertPropSvc start=disabled',
  'sc config WdiServiceHost start=disabled',
  'sc config lmhosts start=disabled',
  'sc config WdiSystemHost start=disabled',
  'sc config TrkWks start=disabled',
  'sc config WerSvc start=disabled',
  'sc config TabletInputService start=disabled',
  'sc config Spooler start=disabled',
  'sc config BcastDVRUserService start=disabled',
  'sc config WMPNetworkSvc start=disabled',
  'sc config diagnosticshub.standardcollector.service start=disabled',
  'sc config DmEnrollmentSvc start=disabled',
  'sc config PNRPAutoReg start=disabled',
  'sc config wlidsvc start=disabled',
  'sc config AXInstSV start=disabled',
  'sc config lfsvc start=disabled',
  'sc config wlidsvc start=disabled',
  'sc config DisplayEnhancementService start=disabled',
  'sc config DiagTrack start=disabled',
  'sc config DusmSvc start=disabled',
  'sc config TabletInputService start=disabled',
  'sc config RetailDemo start=disabled',
  'sc config Fax start=disabled',
  'sc config SharedAccess start=disabled',
  'sc config lfsvc start=disabled',
  'sc config WpcMonSvc start=disabled',
  'sc config SessionEnv start=disabled',
  'sc config MicrosoftEdgeElevationService start=disabled',
  'sc config edgeupdate start=disabled',
  'sc config edgeupdatem start=disabled',
  'sc config autotimesvc start=disabled',
  'sc config TermService start=disabled',
  'sc config SensorDataService start=disabled',
  'sc config SensorService start=disabled',
  'sc config SensrSvc start=disabled',
  'sc config shpamsvc start=disabled',
  'sc config diagnosticshub.standardcollector.service start=disabled',
  'sc config PhoneSvc start=disabled',
  'sc config TapiSrv start=disabled',
  'sc config WalletService start=disabled',
  'sc config TokenBroker start=disabled',
  'sc config WebClient start=disabled',
  'sc config MixedRealityOpenXRSvc start=disabled',
  'sc config stisvc start=disabled',
  'sc config WbioSrvc start=disabled',
  'sc config icssvc start=disabled',
  'sc config Wecsvc start=disabled',
  'sc config XboxGipSvc start=disabled',
  'sc config XblAuthManager start=disabled',
  'sc config XboxNetApiSvc start=disabled',
  'sc config XblGameSave start=disabled',
  'sc config SEMgrSvc start=disabled',
  'sc config iphlpsvc start=disabled',
  'sc config BthAvctpSvc start=disabled',
  'sc config BDESVC start=disabled',
  'sc config cbdhsvc start=disabled',
  'sc config CDPSvc start=disabled',
  'sc config CDPUserSvc start=disabled',
  'sc config DevQueryBroker start=disabled',
  'sc config DevicesFlowUserSvc start=disabled',
  'sc config dmwappushservice start=disabled',
  'sc config DispBrokerDesktopSvc start=disabled',
  'sc config TrkWks start=disabled',
  'sc config EFS start=disabled',
  'sc config fdPHost start=disabled',
  'sc config FDResPub start=disabled',
  'sc config IKEEXT start=disabled',
  'sc config WPDBusEnum start=disabled',
  'sc config PcaSvc start=disabled',
  'sc config RasMan start=disabled',
  'sc config RetailDemo start=disabled',
  'sc config SstpSvc start=disabled',
  'sc config ShellHWDetection start=disabled',
  'sc config SSDPSRV start=disabled',
  'sc config SysMain start=disabled',
  'sc config OneSyncSvc start=disabled',
  'sc config lmhosts start=disabled',
  'sc config UserDataSvc start=disabled',
  'sc config UnistoreSvc start=disabled',
  'sc config Wcmsvc start=disabled',
  'sc config FontCache start=disabled',
  'sc config W32Time start=disabled',
  'sc config tzautoupdate start=disabled',
  'sc config DsSvc start=disabled',
  'sc config diagsvc start=disabled',
  'sc config NetTcpPortSharing start=disabled',
  'sc config ssh-agent start=disabled',
  'sc config SstpSvc start=disabled',
  'sc config wercplsupport start=disabled',
  'sc config WMPNetworkSvc start=disabled',
  'sc config WerSvc start=disabled',
  'sc config BITS start= disabled',
  'sc config InstallService start= disabled',
  'sc config uhssvc start= disabled',
  'sc config UsoSvc start= disabled',
  'sc config wuauserv start= disabled'
  ];

  executeCommands(commands);
}

function executeCommands(commands) {
  if (commands.length === 0) {
    handleSuccess();
    return;
  }

  const command = commands.shift();
  console.log(`Executing command: ${command}`);
  appendToTerminal(`Executing command: ${command}`);
  exec(command, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing command "${command}": ${error.message}`);
      handleSuccess()
      document.getElementById("rocket-conatainer").style.display = "none";
      return;
    }
    if (stderr) {
      console.error(`Error executing command "${command}": ${stderr}`);
      handleSuccess()
      document.getElementById("rocket-conatainer").style.display = "none";
      return;
    }

    console.log(`Command "${command}" executed successfully`);
    appendToTerminal(`Command "${command}" executed successfully`);
    executeCommands(commands);
  });
}

function handleError(errorMessage) {
  setTimeout(() => {
    const errorModal = document.getElementById("errorModal");
    errorModal.style.display = "block";
    errorModal.querySelector(".modal-content-reg").textContent = `Error optimizing speed: ${errorMessage}`;
    setTimeout(() => {
      errorModal.style.display = "none";
    }, 5000);
  }, 3000);
}

function handleSuccess() {
  setTimeout(() => {
    document.getElementById("successModal").style.display = "block";
    setTimeout(() => {
      document.getElementById("successModal").style.display = "none";
    }, 5000);
  }, 3000);

  setTimeout(() => {
    document.getElementById("rocket-conatainer").style.display = "none";
  }, 3000);
}

function appendToTerminal(log) {
  const terminal = document.getElementById("terminal");
  if (terminal) {
    // Create a new paragraph element to display the log
    const logElement = document.createElement("p");
    logElement.textContent = log;

    // Append the log element to the terminal
    terminal.appendChild(logElement);

    // Scroll to the bottom of the terminal to show the latest log
    terminal.scrollTop = terminal.scrollHeight;
  }
}
